### ISSUE TITLE
Need localization for UAE

### ISSUE THREAD

**Issue by alasracc** [Manager-io/Localizations.json#15]
Need localization for UAE

**Comment by lubos** [comment]
Are you familiar how report transformations work?

See https://forum.manager.io/t/report-transformations-no-code-development-platform/35804

You will need to create new business for your country, then create tax codes and finally a report transformation using these tax codes.

Then submit this business file here so it can become country-specific template.

**Comment by lubos** [comment]
Please see https://forum.manager.io/t/contribute-new-country-template/37706
