### ISSUE TITLE
Api amanager integration

### ISSUE THREAD

**Issue by andreaspap1978** [Manager-io/Localizations.json#17]
by using manager extensions we can post data to tax authorities.

How can we get invoice fields using javascript

Required fields are

issuer - company name
customer name
identifier
tax office - custom field on customers
address
type of invoice - sales invoice
invoice line number
item description
quantity
net invoice amount
tax category per item
total taxamount
total net amount
total

**Comment by lubos** [comment]
Before we get to this, can you please first submit new country as per this guide?

https://forum.manager.io/t/contribute-new-country-template/37706

Once we have the basics, I will help you with improving the country-specific functionality.
